# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/android
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/guyo714/Changdroid/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  build-android:
    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          # echo Hello, World!
workflows:
  my-custom-workflow:
    jobs:
      - build-android